### ISSUE TITLE
AttributeError: 'Deta' object has no attribute 'Drive'

### ISSUE THREAD

**Issue by Daveismus** [deta/deta-python#36]
I tried to follow the docs regarding the Deta Drive and got the following traceback:
```
Traceback (most recent call last):
  File "/opt/python/detalib/debugger.py", line 142, in wrap
    result = func(event, context)
  File "/var/task/_entry.py", line 12, in handler
    import main  # noqa
  File "/var/task/main.py", line 14, in <module>
    drive = deta_base.Drive("blob_storage")
AttributeError: 'Deta' object has no attribute 'Drive'
```

this is my code (basically exact the guide): 
```py
from deta import Deta

app = FastAPI()
deta_base = Deta('special-secret-key')
drive = deta_base.Drive("blob_storage")


@app.get("/", response_class=HTMLResponse)
def render():
    return """
    <form action="/upload" enctype="multipart/form-data" method="post">
        <input name="file" type="file">
        <input type="submit">
    </form>
    """

@app.post("/upload")
def upload_img(file: UploadFile = File(...)):
    name = file.filename
    f = file.file
    res = drive.put(name, f)
    return res

@app.get("/download/{name}")
def download_img(name: str):
    res = drive.get(name)
    return StreamingResponse(res.iter_chunks(1024), media_type="image/png")
```

**Comment by Daveismus** [comment]
I only looked at the python specific part and not at the general part of deta-drive. There it is written: add deta as requirement and this fixed the issue
