### ISSUE TITLE
Issue downloading file from drive

### ISSUE THREAD

**Issue by timbusfield** [deta/deta-python#44]
Hi there, I've uploaded a png file to a Deta Drive, I can download it fine using the HTTP API but not using the Python library.

```
def download_file(attachment_stored_filename):
   return drive.get(attachment_stored_filename)
```

```
@app.get("/workorders/attachment/{attachmentStoredFilename}")
async def get_work_order_attachment(attachmentStoredFilename: str):
    drive_streaming_body = deta_drive.download_file(attachmentStoredFilename)
    return StreamingResponse(
        drive_streaming_body.iter_chunks()
    )
```

These are the relevant methods, as you can see I'm simply passing the DriveStreamingBody from the first method into the second and then using iter_chunks as suggested in the tutorial.

The error in the logs is as follows, can anyone suggest where I'm going wrong?

`[ERROR]	2021-07-22T13:29:21.529Z	8dc4c713-992c-474c-bf45-526a5cc71cbe	Exception in ASGI application
Traceback (most recent call last):
  File "/opt/python/detalib/adapters/asgi/protocols/http.py", line 47, in run
    await app(self.scope, self.receive, self.send)
  File "/opt/python/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/python/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/python/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/opt/python/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/python/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/opt/python/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/python/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/opt/python/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/opt/python/starlette/routing.py", line 55, in app
    await response(scope, receive, send)
  File "/opt/python/starlette/responses.py", line 226, in __call__
    (self.listen_for_disconnect, {"receive": receive}),
  File "/opt/python/starlette/concurrency.py", line 24, in run_until_first_complete
    [task.result() for task in done]
  File "/opt/python/starlette/concurrency.py", line 24, in <listcomp>
    [task.result() for task in done]
  File "/opt/python/starlette/responses.py", line 221, in stream_response
    await send({"type": "http.response.body", "body": b"", "more_body": False})
  File "/opt/python/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/opt/python/starlette/middleware/errors.py", line 156, in _send
    await send(message)
  File "/opt/python/detalib/adapters/asgi/protocols/http.py", line 113, in send
    self.response["body"] = body.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
No errors`

**Comment by timbusfield** [comment]
This is the png I used for testing:
http://clipart-library.com/image_gallery/320477.png

**Comment by abdelhai** [comment]
@timbusfield 
You need to pass the media type with the response:

```py
@app.get("/workorders/attachment/{attachmentStoredFilename}")
async def get_work_order_attachment(attachmentStoredFilename: str):
    drive_streaming_body = deta_drive.download_file(attachmentStoredFilename)
    
    return StreamingResponse(drive_streaming_body.iter_chunks(), media_type="image/png")
```

**Comment by timbusfield** [comment]
Thanks very much, I'll make sure I capture the UploadFile.content_type when the file is uploaded so that I can pass it to the StreamingResponse as the media_type when it is downloaded later

**Comment by abdelhai** [comment]
@timbusfield you could easily get the media type on the fly from the file's extension. Look at this simple example: 

https://github.com/abdelhai/drive-starter-python/blob/d71b25d68e81855b8d529e0a6b53991e2e05686f/main.py#L19..L22

**Comment by timbusfield** [comment]
@abdelhai you have more faith in the users than I do :) I've seen a few instances of incorrect file extensions the past.
I'd probably use a module like this one to make the conversion, if I was going to take that approach:
https://docs.python.org/3/library/mimetypes.html

The tool I'm working on should accept any file type really so I'll need to test it on quite a few different file types. Thanks for your help.
