### ISSUE TITLE
The read operation timed out

### ISSUE THREAD

**Issue by thezem** [deta/deta-python#53]
### trying to connect to deta fails , the base is there and has data in it ...

`

 >>> db.get('mybase')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\deta\base.py", line 90, in get
    _, res = self._request("/items/{}".format(key), "GET")
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\deta\service.py", line 76, in _request
    res = self._send_request_with_retry(method, url, headers, body)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\deta\service.py", line 126, in _send_request_with_retry
    res = self.client.getresponse()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1349, in getresponse
    response.begin()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)`

### **socket.timeout: The read operation timed out**

**Comment by aavshr** [comment]
thanks for the report @hazem223 , we will look into it.
