### ISSUE TITLE
AttributeError: module 'orjson' has no attribute 'JSONEncoder' in /opt/python/detalib/helpers.py class CustomJSONEncoder(json.JSONEncoder):

### ISSUE THREAD

**Issue by DaniinXorchenabo** [deta/deta-python#55]
I'm trying to deploy my first app in deta. But I get this error:

```
[2021-09-27T19:17:24+03:00] [ERROR] AttributeError: module 'orjson' has no attribute 'JSONEncoder'
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/_entry.py", line 1, in <module>
    from detalib.handler import handle
  File "/opt/python/detalib/handler.py", line 3, in <module>
    from . import handlers
  File "/opt/python/detalib/handlers.py", line 1, in <module>
    from .event import parse_event
  File "/opt/python/detalib/event.py", line 1, in <module>
    from .helpers import json
  File "/opt/python/detalib/helpers.py", line 16, in <module>
    class CustomJSONEncoder(json.JSONEncoder):
```

i follow first setups in [`fastapi` deploy](https://fastapi.tiangolo.com/deployment/deta/)

My main.py:

```python
from fastapi import FastAPI

app = FastAPI()


@app.get("/")
def read_root():
    return {"Hello": "World"}


@app.get("/items/{item_id}")
def read_item(item_id: int):
    return {"item_id": item_id}
```

my requirements.txt
```
wheel
python-dotenv
fastapi[all]
python-multipart
python-jose[cryptography]
passlib[bcrypt]
uvicorn[standard]
jinja2
dill
pytest-asyncio
httpx
orjson
```

My app in brower:

![image](https://user-images.githubusercontent.com/45897837/134949976-56ffe756-f1ae-4d5d-9ef2-e63fbd683349.png)

My .prog_info
```json
{
"id":<my_id>,
"space":3049,
"runtime":"python3.9",
"name":"tunnel",
"path":"984mpg",
"project":"a0gojavz",
"account":"144798365827",
"region":"ap-southeast-1",
"deps":[
        "wheel",
        "python-dotenv",
        "fastapi[all]",
        "python-multipart",
        "python-jose[cryptography]",
        "passlib[bcrypt]",
        "uvicorn[standard]",
        "jinja2",
        "dill",
        "pytest-asyncio",
        "httpx",
        "orjson"
        ],
"envs":null,
"public":true,
"log_level":"debug",
"cron":""
}

Project structure:

```
.
└── .deta
        └── prog_info
        └── state
└── main.py
└── requirements.txt
```

My deta version: `deta v1.2.0-beta x86_64-windows`

**Comment by aavshr** [comment]
hi sorry this is due an bug with `orjson` and our internal library. You can remove `orjson` in the `requirements.txt`, deploy again and it should resolve the issue. 

If you must use `orjson` unfortunately, we would have to push a fix before you can use it.

**Comment by DaniinXorchenabo** [comment]
Hi, I updated my requirements.txt (Yes, I delete all useless libs):
```
fastapi[all]
```

But I get this error again:
```
[2021-09-30T16:11:57+03:00] [ERROR] AttributeError: module 'orjson' has no attribute 'JSONEncoder'
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/_entry.py", line 1, in <module>
    from detalib.handler import handle
  File "/opt/python/detalib/handler.py", line 3, in <module>
    from . import handlers
  File "/opt/python/detalib/handlers.py", line 1, in <module>
    from .event import parse_event
  File "/opt/python/detalib/event.py", line 1, in <module>
    from .helpers import json
  File "/opt/python/detalib/helpers.py", line 16, in <module>
    class CustomJSONEncoder(json.JSONEncoder):
```

**Comment by aavshr** [comment]
hi `fastapi[all]` also installs `orjson` (https://github.com/tiangolo/fastapi/blob/master/pyproject.toml#L84-#L98) hence the issue.

**Comment by DaniinXorchenabo** [comment]
so, my requirements.txt is empty, but I receive this problem again...

I deleted my deta app and created again. this solved my problem. 

Can I close this lssue?

**Comment by aavshr** [comment]
hi @DaniinXorchenabo , thanks for the report. I'm will close this issue here as it is an issue with our internal lib for micros and not the sdk.
