### ISSUE TITLE
Async Base TimeoutError

### ISSUE THREAD

**Issue by rainyear** [deta/deta-python#59]
I'm using the Deta Base Python Async SDK, got the following TimeoutError exception:
```
Traceback (most recent call last):
  File "/var/task/main.py", line 110, in db_2_notion
    unSynced = await DB.fetch({"synced": False}, limit=1000)
  File "/opt/python/deta/_async/client.py", line 110, in fetch
    async with self._session.post(f"{self._base_url}/query", json=payload) as resp:
  File "/opt/python/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/opt/python/aiohttp/client.py", line 634, in _request
    break
  File "/opt/python/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

The query line:
`await DB.fetch({"synced": False}, limit=1000)`

It works well in my local env, but got the error from `deta logs` command

**Comment by abdelhai** [comment]
hi @rainyear apology for not replying faster as this issue was low on our priority list. does this issue still persist?
